zap:
  error-path: /logs/error
  other-path: /logs/other
  max-size: 300
  max-age: 30
  max-backup: 5
consul:
  addr: "10.0.24.3:8500"
grpc:
  host: "10.0.24.3:8848"
#mysql:
#  dsn: root:abc123456@tcp(127.0.0.1:3306)/gateway?charset=utf8mb4&parseTime=True&loc=Local
#  max-open-conn: 20
#  max-idle-conn: 10
#  max-conn-life-time: 100
#server:
#  addr: "127.0.0.1:8000"
#
#cluster:
#  host: "127.0.0.1" # 网关的host，用于访问。
#  port: 8880 # http的端口
#  ssl-port: 4433 # https的端口
redis:
  host: "10.0.24.3" # 网关的host，用于访问。
  port: 6379 # http的端口
  password: "abc123456"